# @diegotorres50: import routes from a controller directory
services_app:
    resource: "@ServicesAppBundle/Controller"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
